# rubocop:disable Style/LeadingCommentSpace
#ruby-gemset=docker-tools
# rubocop:enable Style/LeadingCommentSpace
source "https://rubygems.org"
ruby "2.3.1"
"docker-tools"
# Specify your gem's dependencies in docker-tasks.gemspec
gemspec
